Repository ember-intl/ember-intl, pull requests merged in 2023-06, with the labels that each got.

#1754 Added lerna-changelog and concurrently
  .github/workflows/ci-cd.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: enhance: dependency

#1748 fix: Filepath matching is overly-eager when namespace wrapping
  lib/broccoli/translation-reducer/utils/wrap-with-namespace-if-needed.js
  tests-node/unit/broccoli/translation-reducer/wrap-with-namespace-if-needed.js
Labels: bug

#1749 Enable embroider test scenarios (with allowedToFail set to true)
  .github/workflows/ci-cd.yml
  config/ember-try.js
  package.json
  yarn.lock
Labels: enhance: documentation

#1733 feat: update runtime requirements screenshots
  tests/dummy/public/images/datetimeformat.png
  tests/dummy/public/images/getcanonicallocales.png
  tests/dummy/public/images/locale.png
  tests/dummy/public/images/numberformat.png
  tests/dummy/public/images/pluralrules.png
  tests/dummy/public/images/relativetimeformat.png
Labels: enhance: documentation

#1730 chore: remove time-zone comment in format-list test
  tests/unit/helpers/format-list-test.ts
Labels: enhance: documentation

#1756 Checked compatibilities with Ember 4.4, 4.8, and 4.12
  .github/workflows/ci-cd.yml
  config/ember-try.js
  package.json
Labels: enhance: documentation
