Repository ember-intl/ember-intl, pull requests merged in 2024-09, with the labels that each got.

#1922 Made pnpm settings stricter
  .changeset/hot-drinks-nail.md
  .npmrc
  pnpm-lock.yaml
Labels: enhance: dependency

#1923 Updated development dependencies
  configs/ember-template-lint/package.json
  configs/eslint/ember/package.json
  configs/eslint/node/package.json
  configs/eslint/yaml/package.json
  configs/prettier/package.json
  configs/stylelint/package.json
  configs/testem/package.json
  configs/typescript/package.json
  docs/ember-intl/package.json
  docs/my-app-with-fallbacks/package.json
  docs/my-app-with-lazy-loaded-translations/package.json
  docs/my-app-with-namespace-from-folders/package.json
  docs/my-app/package.json
  docs/my-classic-app-with-lazy-loaded-translations/package.json
  docs/my-classic-app/package.json
  docs/my-v1-addon/package.json
  docs/my-v1-engine/package.json
  docs/my-v2-addon/package.json
  package.json
  packages/ember-intl/package.json
  pnpm-lock.yaml
  tests/ember-intl-node/package.json
  tests/ember-intl/package.json
Labels: enhance: dependency

#1918 Listed @ember/test-helpers as a peer dependency
  .changeset/polite-poets-share.md
  .github/workflows/ci-cd.yml
  docs/ember-intl/package.json
  docs/my-app-with-fallbacks/package.json
  docs/my-app-with-lazy-loaded-translations/package.json
  docs/my-app-with-namespace-from-folders/package.json
  docs/my-app/package.json
  docs/my-classic-app-with-lazy-loaded-translations/package.json
  docs/my-classic-app/package.json
  docs/my-v1-addon/package.json
  docs/my-v1-engine/package.json
  docs/my-v2-addon/package.json
  packages/ember-intl/package.json
  pnpm-lock.yaml
  tests/ember-intl/config/ember-try.js
  tests/ember-intl/package.json
Labels: bug

#1921 Created a page that explains how to use ember-intl's helpers in <template> tag
  .changeset/real-years-jog.md
  docs/ember-intl/app/router.js
  docs/ember-intl/app/templates/docs.hbs
  docs/ember-intl/app/templates/docs/helpers/template-tag.md
Labels: enhance: documentation
