Repository ember-intl/ember-intl, pull requests merged in 2024-04, with the labels that each got.

#1843 Removed dependentKeyCompat decorator
  .changeset/dull-mangos-drum.md
  packages/ember-intl/addon/services/intl.js
  tests/ember-intl/tests/integration/components/macros-test.ts
  tests/ember-intl/tests/unit/macros/intl-test.ts
  tests/ember-intl/tests/unit/macros/t-test.ts
Labels: bug, breaking

#1854 Removed @intl and @t macros
  .changeset/smooth-cobras-wink.md
  docs/ember-intl/app/templates/docs/guide/translating-text.md
  packages/ember-intl/addon/macros/index.ts
  packages/ember-intl/addon/macros/intl.ts
  packages/ember-intl/addon/macros/t.ts
  tests/ember-intl/app/components/macros.hbs
  tests/ember-intl/app/components/macros.ts
Labels: breaking

#1855 Removed blueprints for ember g translation
  .changeset/clever-queens-hug.md
  packages/ember-intl/blueprints/translation/files/__prefix__/__name__.yaml
  packages/ember-intl/blueprints/translation/index.js
  packages/ember-intl/lib/utils/is-valid-locale-format.js
  packages/ember-intl/package.json
  pnpm-lock.yaml
  tests/ember-intl-node/tests/blueprints/translation/beforeInstall-locale-is-not-valid-test.js
  tests/ember-intl-node/tests/blueprints/translation/beforeInstall-locale-is-valid-test.js
Labels: breaking

#1856 Began to document breaking changes in ember-intl@7.0.0
  .changeset/empty-ghosts-fix.md
  docs/ember-intl/app/router.js
  docs/ember-intl/app/templates/docs.hbs
  docs/ember-intl/app/templates/docs/migration/v2.md
  docs/ember-intl/app/templates/docs/migration/v3.md
  docs/ember-intl/app/templates/docs/migration/v4.md
  docs/ember-intl/app/templates/docs/migration/v5.md
  docs/ember-intl/app/templates/docs/migration/v6.md
  docs/ember-intl/app/templates/docs/migration/v7.md
Labels: enhance: documentation

#1857 Removed @types/htmlbars-inline-precompile from devDependencies
  .changeset/stale-gifts-allow.md
  packages/ember-intl/package.json
  packages/ember-intl/types/global.d.ts
  pnpm-lock.yaml
Labels: enhance: dependency

#1859 Added CHANGELOG.md and tsconfig.json to .npmignore
  packages/ember-intl/.npmignore
Labels: enhance: dependency

#1860 Removed incorrect passage in quickstart for addons. Updated the migration guide to v7.
  .changeset/popular-fireants-double.md
  docs/ember-intl/app/templates/docs/getting-started/quickstart-addons.md
  docs/ember-intl/app/templates/docs/migration/v7.md
Labels: enhance: documentation

#1861 Updated minimum requirements for Ember, Node, and TypeScript
  .changeset/proud-sloths-compare.md
  .github/workflows/ci-cd.yml
  README.md
  configs/ember-template-lint/package.json
  configs/eslint/ember/package.json
  configs/eslint/node/package.json
  configs/prettier/package.json
  configs/stylelint/package.json
  configs/testem/package.json
  configs/typescript/package.json
  docs/ember-intl/package.json
  docs/my-app/package.json
  docs/my-v1-addon/package.json
  docs/my-v2-addon/package.json
  package.json
  packages/ember-intl/README.md
  packages/ember-intl/package.json
  tests/ember-intl-node/package.json
  tests/ember-intl/config/ember-try.js
  tests/ember-intl/package.json
Labels: breaking

#1862 Updated development dependencies
  configs/ember-template-lint/package.json
  configs/eslint/ember/package.json
  configs/eslint/node/package.json
  configs/stylelint/package.json
  configs/typescript/package.json
  docs/ember-intl/package.json
  docs/my-app/package.json
  docs/my-v1-addon/package.json
  docs/my-v2-addon/package.json
  packages/ember-intl/package.json
  pnpm-lock.yaml
  tests/ember-intl-node/package.json
  tests/ember-intl/package.json
Labels: enhance: dependency

#1865 Recommend using types/global.d.ts for glint
  .changeset/famous-olives-lie.md
  docs/ember-intl/app/templates/docs/getting-started/quickstart.md
Labels: enhance: documentation
