Repository ember-intl/ember-intl, pull requests merged in 2024-12, with the labels that each got.

#1932 Removed the usages of Ember Helper's recompute. Removed eventemitter3 as a dependency.
  .changeset/mighty-donuts-move.md
  packages/ember-intl/addon/helpers/format-date.ts
  packages/ember-intl/addon/helpers/format-list.ts
  packages/ember-intl/addon/helpers/format-message.ts
  packages/ember-intl/addon/helpers/format-number.ts
  packages/ember-intl/addon/helpers/format-relative.ts
  packages/ember-intl/addon/helpers/format-time.ts
  packages/ember-intl/addon/helpers/t.ts
  packages/ember-intl/addon/services/intl.ts
  packages/ember-intl/package.json
  pnpm-lock.yaml
  tests/ember-intl/tests/unit/services/intl-test.ts
Labels: enhance: dependency, enhance: code

#1933 Updated dependencies
  .changeset/poor-clouds-bow.md
  configs/ember-template-lint/package.json
  configs/eslint/ember/package.json
  configs/eslint/node/package.json
  configs/eslint/yaml/package.json
  configs/prettier/package.json
  configs/stylelint/package.json
  configs/testem/package.json
  configs/typescript/package.json
  docs/ember-intl/config/ember-cli-update.json
  docs/ember-intl/package.json
  docs/ember-intl/tests/test-helper.ts
  docs/my-app-with-fallbacks/config/ember-cli-update.json
  docs/my-app-with-fallbacks/package.json
  docs/my-app-with-fallbacks/tests/test-helper.ts
  docs/my-app-with-lazy-loaded-translations/config/ember-cli-update.json
  docs/my-app-with-lazy-loaded-translations/package.json
  docs/my-app-with-lazy-loaded-translations/tests/test-helper.ts
  docs/my-app-with-namespace-from-folders/config/ember-cli-update.json
  docs/my-app-with-namespace-from-folders/package.json
  docs/my-app-with-namespace-from-folders/tests/test-helper.ts
  docs/my-app/config/ember-cli-update.json
  docs/my-app/package.json
  docs/my-app/tests/test-helper.ts
  docs/my-classic-app-with-lazy-loaded-translations/config/ember-cli-update.json
  docs/my-classic-app-with-lazy-loaded-translations/package.json
  docs/my-classic-app-with-lazy-loaded-translations/tests/test-helper.ts
  docs/my-classic-app/config/ember-cli-update.json
  docs/my-classic-app/package.json
  docs/my-classic-app/tests/test-helper.ts
  docs/my-v1-addon/package.json
  docs/my-v1-addon/tests/dummy/config/ember-cli-update.json
  docs/my-v1-engine/package.json
  docs/my-v1-engine/tests/dummy/config/ember-cli-update.json
  docs/my-v2-addon/package.json
  docs/my-v2-addon/src/components/select-locale.ts
  package.json
  packages/ember-intl/package.json
  packages/ember-intl/tests/dummy/config/ember-cli-update.json
  packages/ember-intl/tests/test-helper.ts
  patches/ember-cli-addon-docs@7.0.1.patch
  pnpm-lock.yaml
  tests/ember-intl-node/package.json
  tests/ember-intl/config/ember-cli-update.json
  tests/ember-intl/package.json
  tests/ember-intl/tests/test-helper.ts
Labels: enhance: dependency

#1934 Replaced ember-lts-5.4 and ember-lts-5.8 with ember-lts-5.12
  .changeset/forty-tomatoes-enjoy.md
  .github/workflows/ci-cd.yml
  tests/ember-intl/config/ember-try.js
Labels: enhance: documentation

#1931 Created {{format-date-range}} helper
  .changeset/polite-dryers-pump.md
  packages/ember-intl/addon/-private/formatjs/format-date-range.ts
  packages/ember-intl/addon/-private/formatjs/index.ts
  packages/ember-intl/addon/helpers/format-date-range.ts
  packages/ember-intl/addon/index.ts
  packages/ember-intl/addon/services/intl.ts
  packages/ember-intl/addon/template-registry.ts
  packages/ember-intl/app/helpers/format-date-range.js
  tests/ember-intl/.template-lintrc.js
  tests/ember-intl/app/templates/index.hbs
  tests/ember-intl/app/templates/smoke-tests.hbs
  tests/ember-intl/tests/acceptance/smoke-tests-test.ts
  tests/ember-intl/tests/integration/helpers/format-date-range/input-is-a-date-test.ts
  tests/ember-intl/tests/integration/helpers/format-date-range/input-is-a-string-test.ts
  tests/ember-intl/tests/integration/helpers/format-date-range/input-is-an-integer-test.ts
  tests/ember-intl/tests/integration/helpers/format-date-range/input-is-falsy-test.ts
  tests/ember-intl/tests/integration/helpers/format-date-range/input-is-not-well-defined-test.ts
  tests/ember-intl/tests/integration/helpers/format-date-range/template-tag-support-test.gts
Labels: enhance: code

#1935 Documented {{format-date-range}} helper
  .changeset/polite-ducks-pretend.md
  docs/ember-intl/app/controllers/docs/helpers/format-date-range.ts
  docs/ember-intl/app/router.js
  docs/ember-intl/app/snippets/docs/helpers/format-date-range/example-1/component.ts
  docs/ember-intl/app/snippets/docs/helpers/format-date-range/example-1/template.hbs
  docs/ember-intl/app/snippets/docs/helpers/format-date-range/example-3/component.ts
  docs/ember-intl/app/snippets/docs/helpers/format-date-range/example-3/template.hbs
  docs/ember-intl/app/snippets/docs/helpers/format-date-range/example-4/component.ts
  docs/ember-intl/app/snippets/docs/helpers/format-date-range/example-4/template.hbs
  docs/ember-intl/app/templates/docs.hbs
  docs/ember-intl/app/templates/docs/helpers/format-date-range.md
  docs/ember-intl/app/templates/docs/helpers/format-date.md
  docs/ember-intl/app/templates/docs/helpers/template-tag.md
  docs/ember-intl/app/templates/docs/services/intl-part-1.md
Labels: enhance: documentation

#1936 Added missing changelogs
  README.md
  packages/ember-intl/CHANGELOG.md
  packages/ember-intl/README.md
Labels: enhance: documentation

#1937 Updated docs-apps
  .changeset/nervous-kangaroos-punch.md
  docs/ember-intl/app/templates/docs/helpers/format-date-range.md
  docs/ember-intl/package.json
  docs/my-v2-addon/.gitignore
  docs/my-v2-addon/.prettierignore
  docs/my-v2-addon/unpublished-development-types/ember-intl.d.ts
Labels: enhance: documentation
