Repository ember-intl/ember-intl, pull requests merged in 2024-05, with the labels that each got.

#1864 Remove broccoli-merge-files
  .changeset/friendly-cooks-destroy.md
  packages/ember-intl/index.js
  packages/ember-intl/lib/broccoli/translation-reducer/index.js
  packages/ember-intl/package.json
  pnpm-lock.yaml
  tests/ember-intl-node/tests/lib/broccoli/translation-reducer/index/base-case-test.js
Labels: enhance: dependency, enhance: code

#1872 Updated development dependencies
  .changeset/perfect-mangos-bathe.md
  configs/eslint/ember/app/index.js
  configs/eslint/ember/package.json
  configs/eslint/ember/patch.js
  configs/eslint/ember/v1-addon/index.js
  configs/eslint/node/package.json
  docs/ember-intl/.eslintignore
  docs/ember-intl/app/snippets/docs/helpers/format-message/example-1/component.js
  docs/ember-intl/config/ember-cli-update.json
  docs/ember-intl/package.json
  docs/my-app-with-lazy-loaded-translations/.eslintignore
  docs/my-app-with-lazy-loaded-translations/config/ember-cli-update.json
  docs/my-app-with-lazy-loaded-translations/package.json
  docs/my-app-with-namespace-from-folders/.eslintignore
  docs/my-app-with-namespace-from-folders/config/ember-cli-update.json
  docs/my-app-with-namespace-from-folders/package.json
  docs/my-app/.eslintignore
  docs/my-app/config/ember-cli-update.json
  docs/my-app/package.json
  docs/my-classic-app/.eslintignore
  docs/my-classic-app/config/ember-cli-update.json
  docs/my-classic-app/package.json
  docs/my-v1-addon/.eslintignore
  docs/my-v1-addon/.eslintrc.js
  docs/my-v1-addon/package.json
  docs/my-v1-addon/tests/dummy/config/ember-cli-update.json
  docs/my-v2-addon/.eslintrc.js
  docs/my-v2-addon/package.json
  package.json
  packages/ember-intl/.eslintignore
  packages/ember-intl/.eslintrc.js
  packages/ember-intl/addon/services/intl.js
  packages/ember-intl/package.json
  packages/ember-intl/tests/dummy/config/ember-cli-update.json
  pnpm-lock.yaml
  tests/ember-intl/.eslintignore
  tests/ember-intl/config/ember-cli-update.json
  tests/ember-intl/package.json
Labels: enhance: dependency

#1874 Pinned ember-beta and ember-canary
  tests/ember-intl/config/ember-try.js
Labels: bug, enhance: documentation

#1873 Extracted <SelectLocale> to my-v2-addon
  .changeset/fresh-cheetahs-approve.md
  docs/my-app-with-lazy-loaded-translations/package.json
  docs/my-app-with-lazy-loaded-translations/tests/helpers/components/select-locale.ts
  docs/my-app-with-lazy-loaded-translations/tests/helpers/index.ts
  docs/my-app-with-lazy-loaded-translations/types/my-app-with-lazy-loaded-translations/index.d.ts
  docs/my-app-with-namespace-from-folders/app/components/select-locale.hbs
  docs/my-app-with-namespace-from-folders/app/components/select-locale.ts
  docs/my-app-with-namespace-from-folders/package.json
  docs/my-app-with-namespace-from-folders/tests/helpers/index.ts
  docs/my-app-with-namespace-from-folders/tests/integration/components/select-locale-test.ts
  docs/my-app-with-namespace-from-folders/translations/components/select-locale/de-de.yml
  docs/my-app-with-namespace-from-folders/translations/components/select-locale/en-us.yml
  docs/my-app-with-namespace-from-folders/types/my-app-with-namespace-from-folders/index.d.ts
  docs/my-app/app/components/select-locale.hbs
  docs/my-app/app/components/select-locale.ts
  docs/my-app/package.json
  docs/my-app/tests/helpers/components/select-locale.ts
  docs/my-app/tests/helpers/index.ts
  docs/my-app/types/my-app/index.d.ts
  docs/my-classic-app/app/components/select-locale.hbs
  docs/my-classic-app/app/components/select-locale.ts
  docs/my-classic-app/package.json
  docs/my-classic-app/tests/helpers/components/select-locale.ts
  docs/my-classic-app/tests/helpers/index.ts
  docs/my-classic-app/translations/components/select-locale/de-de.yml
  docs/my-classic-app/translations/components/select-locale/en-us.yml
  docs/my-classic-app/types/my-classic-app/index.d.ts
  docs/my-v2-addon/package.json
  docs/my-v2-addon/rollup.config.mjs
  docs/my-v2-addon/src/components/select-locale.hbs
  docs/my-v2-addon/src/components/select-locale.ts
  docs/my-v2-addon/src/index.ts
  docs/my-v2-addon/src/template-registry.ts
  docs/my-v2-addon/src/test-support.ts
  docs/my-v2-addon/src/test-support/components/select-locale.ts
  docs/my-v2-addon/translations/components/select-locale/de-de.yml
  docs/my-v2-addon/translations/components/select-locale/en-us.yml
  docs/my-v2-addon/unpublished-development-types/index.d.ts
  pnpm-lock.yaml
Labels: enhance: documentation, enhance: code

#1876 Removed 3 dependencies
  .changeset/dry-houses-eat.md
  packages/ember-intl/lib/broccoli/translation-reducer/index.js
  packages/ember-intl/lib/broccoli/translation-reducer/utils/wrap-with-namespace-if-needed.js
  packages/ember-intl/package.json
  pnpm-lock.yaml
Labels: enhance: dependency, enhance: code

#1847 Required locale in setupIntl()
  .changeset/honest-ravens-vanish.md
  docs/ember-intl/app/templates/docs/guide/testing.md
  docs/ember-intl/app/templates/docs/migration/v7.md
  docs/ember-intl/tests/helpers/index.ts
  docs/ember-intl/tests/integration/components/locale-switcher-test.ts
  docs/my-app-with-lazy-loaded-translations/tests/helpers/index.ts
  docs/my-app-with-lazy-loaded-translations/tests/integration/components/select-locale-test.ts
  docs/my-app-with-namespace-from-folders/tests/helpers/index.ts
  docs/my-app-with-namespace-from-folders/tests/integration/components/select-locale-test.ts
  docs/my-app/tests/helpers/index.ts
  docs/my-app/tests/integration/components/select-locale-test.ts
  docs/my-classic-app/tests/helpers/index.ts
  docs/my-classic-app/tests/integration/components/select-locale-test.ts
  docs/my-v1-addon/tests/helpers/index.ts
  docs/my-v1-engine/tests/helpers/index.ts
  packages/ember-intl/addon-test-support/setup-intl.ts
  packages/ember-intl/addon/services/intl.js
  packages/ember-intl/tests/helpers/index.ts
  tests/ember-intl/tests/helpers/index.ts
  tests/ember-intl/tests/integration/components/lazy-hello-test.ts
  tests/ember-intl/tests/integration/test-helpers/index-test.ts
  tests/ember-intl/tests/unit/services/intl-test.ts
Labels: bug, breaking

#1877 Required locale in addTranslations()
  .changeset/beige-bears-fold.md
  docs/ember-intl/app/templates/docs/guide/testing.md
  docs/ember-intl/app/templates/docs/migration/v7.md
  packages/ember-intl/addon-test-support/add-translations.ts
  packages/ember-intl/addon-test-support/setup-intl.ts
  tests/ember-intl/tests/integration/components/lazy-hello-test.ts
  tests/ember-intl/tests/integration/test-helpers/index-test.ts
Labels: breaking

#1878 Minimized test helpers API
  .changeset/eight-eagles-cheer.md
  docs/ember-intl/app/templates/docs/migration/v7.md
  packages/ember-intl/addon-test-support/add-translations.ts
  packages/ember-intl/addon-test-support/index.ts
  packages/ember-intl/addon-test-support/set-locale.ts
  packages/ember-intl/addon-test-support/setup-intl.ts
  packages/ember-intl/addon-test-support/t.ts
  tests/ember-intl/tests/integration/helpers/t/missingMessage-is-false-test.ts
  tests/ember-intl/tests/integration/test-helpers/index-test.ts
  tests/ember-intl/tests/unit/services/intl-test.ts
Labels: bug, breaking

#1880 Added @babel/core as a dependency (required by ember-cli-babel@v8)
  .changeset/sweet-radios-care.md
  docs/my-v2-addon/package.json
  packages/ember-intl/package.json
  pnpm-lock.yaml
Labels: bug, enhance: dependency

#1882 Refactored code in lib
  .changeset/lucky-buttons-draw.md
  packages/ember-intl/blueprints/ember-intl/files/__config__/ember-intl.js
  packages/ember-intl/index.js
  packages/ember-intl/lib/broccoli/build-translation-tree.js
  packages/ember-intl/lib/broccoli/translation-reducer/index.js
  packages/ember-intl/lib/broccoli/translation-reducer/linter/extract-icu-arguments.js
  packages/ember-intl/lib/broccoli/translation-reducer/linter/find-missing-translations.js
  packages/ember-intl/lib/broccoli/translation-reducer/linter/index.js
  packages/ember-intl/lib/broccoli/translation-reducer/utils/wrap-with-namespace-if-needed.js
  packages/ember-intl/lib/default-config.js
  packages/ember-intl/lib/logger.js
  packages/ember-intl/lib/message-validator/validate-message.js
  packages/ember-intl/lib/utils/find-engine.js
  tests/ember-intl-node/package.json
  tests/ember-intl-node/tests/message-validator/ast-traverse-test.js
  tests/ember-intl-node/tests/message-validator/ordinal-categories-test.js
  tests/ember-intl-node/tests/message-validator/plural-categories-test.js
  tests/ember-intl-node/tests/message-validator/validate-message-test.js
  tests/ember-intl-node/unit/index-test.js
Labels: enhance: code

#1883 Patched #1877 and #1882
  .changeset/soft-ducks-leave.md
  packages/ember-intl/addon-test-support/set-locale.ts
  packages/ember-intl/lib/utils/find-engine.js
  tests/ember-intl/tests/acceptance/smoke-tests-test.ts
Labels: bug, breaking

#1884 Patched docs-apps
  .changeset/slow-lamps-drum.md
  configs/eslint/ember/v2-addon/index.js
  docs/ember-intl/app/routes/application.ts
  docs/my-app-with-lazy-loaded-translations/app/controllers/index.ts
  docs/my-app-with-lazy-loaded-translations/app/routes/application.ts
  docs/my-app-with-lazy-loaded-translations/app/styles/app.css
  docs/my-app-with-lazy-loaded-translations/app/templates/index.hbs
  docs/my-app-with-lazy-loaded-translations/tests/acceptance/index-test.ts
  docs/my-app-with-namespace-from-folders/app/controllers/index.ts
  docs/my-app-with-namespace-from-folders/app/routes/application.ts
  docs/my-app-with-namespace-from-folders/app/styles/app.css
  docs/my-app-with-namespace-from-folders/app/templates/index.hbs
  docs/my-app-with-namespace-from-folders/tests/acceptance/index-test.ts
  docs/my-app/app/controllers/index.ts
  docs/my-app/app/routes/application.ts
  docs/my-app/app/styles/app.css
  docs/my-app/app/templates/index.hbs
  docs/my-app/app/utils/intl/missing-message.js
  docs/my-app/tests/acceptance/index-test.ts
  docs/my-classic-app/app/controllers/index.ts
  docs/my-classic-app/app/routes/application.ts
  docs/my-classic-app/app/styles/app.css
  docs/my-classic-app/app/templates/index.hbs
  docs/my-classic-app/app/utils/intl/missing-message.js
  docs/my-classic-app/tests/acceptance/index-test.ts
  docs/my-classic-app/tests/acceptance/my-v1-engine-test.ts
  docs/my-v1-engine/addon/controllers/index.ts
  docs/my-v1-engine/addon/templates/index.hbs
  docs/my-v1-engine/package.json
  docs/my-v2-addon/.eslintrc.js
  docs/my-v2-addon/src/components/select-locale.ts
  pnpm-lock.yaml
Labels: enhance: documentation

#1886 Allowed end-developers to specify what to do when a translation is missing
  .changeset/thick-mayflies-wave.md
  docs/my-app/app/routes/application.ts
  docs/my-app/app/utils/intl/missing-message.js
  docs/my-classic-app/app/routes/application.ts
  docs/my-classic-app/app/utils/intl/missing-message.js
  packages/ember-intl/addon-test-support/-private/missing-message.ts
  packages/ember-intl/addon-test-support/-private/on-missing-translation.ts
  packages/ember-intl/addon-test-support/setup-intl.ts
  packages/ember-intl/addon/-private/utils/missing-message.ts
  packages/ember-intl/addon/services/intl.ts
  packages/ember-intl/app/utils/intl/missing-message.js
  tests/ember-intl/tests/unit/services/intl-test.ts
Labels: breaking, enhance: code

#1887 Allowed end-developers to specify what to do when @formatjs errors
  .changeset/three-steaks-sit.md
  packages/ember-intl/addon/services/intl.ts
  tests/ember-intl/tests/unit/services/intl-test.ts
Labels: enhance: code

#1888 Called normalizeLocale() when reading or writing to this._intls
  .changeset/eighty-ladybugs-brush.md
  packages/ember-intl/addon/-private/utils/locale.ts
  packages/ember-intl/addon/services/intl.ts
Labels: bug

#1889 Restricted API for helpers
  .changeset/fuzzy-rings-shop.md
  packages/ember-intl/addon-test-support/add-translations.ts
  packages/ember-intl/addon-test-support/set-locale.ts
  packages/ember-intl/addon-test-support/setup-intl.ts
  packages/ember-intl/addon-test-support/t.ts
  packages/ember-intl/addon/helpers/format-date.ts
  packages/ember-intl/addon/helpers/format-list.ts
  packages/ember-intl/addon/helpers/format-message.ts
  packages/ember-intl/addon/helpers/format-number.ts
  packages/ember-intl/addon/helpers/format-relative.ts
  packages/ember-intl/addon/helpers/format-time.ts
  packages/ember-intl/addon/helpers/t.ts
  packages/ember-intl/package.json
  pnpm-lock.yaml
  tests/ember-intl/tests/integration/helpers/format-date/api-that-may-be-deprecated-test.ts
  tests/ember-intl/tests/integration/helpers/format-date/input-is-falsy-test.ts
  tests/ember-intl/tests/integration/helpers/format-list/api-that-may-be-deprecated-test.ts
  tests/ember-intl/tests/integration/helpers/format-list/input-is-falsy-test.ts
  tests/ember-intl/tests/integration/helpers/format-message/api-that-may-be-deprecated-test.ts
  tests/ember-intl/tests/integration/helpers/format-message/input-is-an-icu-message-syntax-test.ts
  tests/ember-intl/tests/integration/helpers/format-message/input-is-falsy-test.ts
  tests/ember-intl/tests/integration/helpers/format-message/input-is-not-well-defined-test.ts
  tests/ember-intl/tests/integration/helpers/format-number/api-that-may-be-deprecated-test.ts
  tests/ember-intl/tests/integration/helpers/format-number/input-is-falsy-test.ts
  tests/ember-intl/tests/integration/helpers/format-relative/api-that-may-be-deprecated-test.ts
  tests/ember-intl/tests/integration/helpers/format-relative/input-is-falsy-test.ts
  tests/ember-intl/tests/integration/helpers/format-time/api-that-may-be-deprecated-test.ts
  tests/ember-intl/tests/integration/helpers/format-time/input-is-falsy-test.ts
  tests/ember-intl/tests/integration/helpers/t/api-that-may-be-deprecated-test.ts
  tests/ember-intl/tests/integration/helpers/t/input-is-a-translation-key-test.ts
  tests/ember-intl/tests/integration/helpers/t/input-is-falsy-test.ts
  tests/ember-intl/tests/integration/helpers/t/input-is-not-well-defined-test.ts
Labels: breaking, enhance: code
