Repository ember-intl/ember-intl, pull requests merged in 2025-06, with the labels that each got.

#1968 Updated dependencies
  .changeset/chubby-turkeys-cross.md
  configs/ember-template-lint/package.json
  configs/eslint/ember/package.json
  configs/eslint/node/package.json
  configs/stylelint/package.json
  docs/ember-intl/package.json
  docs/my-v1-addon/package.json
  docs/my-v1-app-with-fallbacks/package.json
  docs/my-v1-app-with-lazy-loaded-translations/package.json
  docs/my-v1-app-with-namespace-from-folders/package.json
  docs/my-v1-app/package.json
  docs/my-v1-classic-app-with-lazy-loaded-translations/package.json
  docs/my-v1-classic-app/package.json
  docs/my-v1-engine/package.json
  docs/my-v2-addon/package.json
  docs/my-v2-app/package.json
  package.json
  packages/ember-intl/package.json
  pnpm-lock.yaml
  tests/ember-intl-node/package.json
  tests/ember-intl/package.json
Labels: enhance: dependency

#1972 Deprecated defining formats in app/formats.js
  .changeset/bright-clowns-trade.md
  docs/ember-intl/app/ember-intl.ts
  docs/ember-intl/app/routes/application.ts
  docs/ember-intl/app/templates/docs/services/intl-part-2.md
  packages/ember-intl/addon/-private/formatjs/formats.ts
  packages/ember-intl/addon/-private/formatjs/index.ts
  packages/ember-intl/addon/index.ts
  packages/ember-intl/addon/services/intl.ts
Labels: enhance: code

#1973 Added tests for setFormats()
  .changeset/soft-meals-sing.md
  tests/ember-intl/app/ember-intl.ts
  tests/ember-intl/app/routes/application.ts
  tests/ember-intl/tests/integration/helpers/format-date/input-is-a-date-test.ts
  tests/ember-intl/tests/integration/helpers/format-date/input-is-a-string-test.ts
  tests/ember-intl/tests/integration/helpers/format-date/input-is-an-integer-test.ts
  tests/ember-intl/tests/integration/helpers/format-number/input-is-a-currency-test.ts
  tests/ember-intl/tests/integration/helpers/format-time/input-is-a-date-test.ts
  tests/ember-intl/tests/integration/helpers/format-time/input-is-a-string-test.ts
  tests/ember-intl/tests/integration/helpers/format-time/input-is-an-integer-test.ts
  tests/ember-intl/tests/unit/services/intl/setFormats-test.ts
Labels: enhance: documentation

#1974 Passed the correct locales to _onMissingTranslation()
  .changeset/long-parrots-invent.md
  packages/ember-intl/addon/services/intl.ts
  tests/ember-intl/tests/integration/helpers/t/input-is-a-translation-key-test.ts
Labels: bug

#1966 Documented how to auto-generate keys
  .changeset/free-buttons-jog.md
  docs/ember-intl/app/router.js
  docs/ember-intl/app/templates/docs.hbs
  docs/ember-intl/app/templates/docs/advanced/auto-generating-keys.md
Labels: enhance: documentation

#1978 Updated dependencies
  .changeset/better-toes-jump.md
  configs/ember-template-lint/package.json
  configs/eslint/ember/package.json
  configs/eslint/node/package.json
  configs/eslint/yaml/package.json
  configs/prettier/package.json
  docs/ember-intl/config/ember-cli-update.json
  docs/ember-intl/package.json
  docs/my-v1-addon/package.json
  docs/my-v1-addon/tests/dummy/config/ember-cli-update.json
  docs/my-v1-app-with-fallbacks/config/ember-cli-update.json
  docs/my-v1-app-with-fallbacks/package.json
  docs/my-v1-app-with-lazy-loaded-translations/config/ember-cli-update.json
  docs/my-v1-app-with-lazy-loaded-translations/package.json
  docs/my-v1-app-with-namespace-from-folders/config/ember-cli-update.json
  docs/my-v1-app-with-namespace-from-folders/package.json
  docs/my-v1-app/config/ember-cli-update.json
  docs/my-v1-app/package.json
  docs/my-v1-classic-app-with-lazy-loaded-translations/config/ember-cli-update.json
  docs/my-v1-classic-app-with-lazy-loaded-translations/package.json
  docs/my-v1-classic-app/config/ember-cli-update.json
  docs/my-v1-classic-app/package.json
  docs/my-v1-engine/package.json
  docs/my-v1-engine/tests/dummy/config/ember-cli-update.json
  docs/my-v2-addon/package.json
  docs/my-v2-app-with-lazy-loaded-translations/config/ember-cli-update.json
  docs/my-v2-app-with-lazy-loaded-translations/package.json
  docs/my-v2-app/config/ember-cli-update.json
  docs/my-v2-app/package.json
  packages/ember-intl/package.json
  pnpm-lock.yaml
  tests/ember-intl-node/package.json
  tests/ember-intl/package.json
  tests/ember-intl/tests/integration/helpers/format-relative/input-is-a-number-test.ts
  tests/ember-intl/tests/unit/services/intl/formatRelative-test.ts
Labels: enhance: dependency
